version: "3.9"  
services:
  ansible:
    build: 
      context: ./ansible/ansible_base
      dockerfile: Dockerfile
    container_name: ansible_controller
    volumes:
      - type: bind
        source: ./ansible/ansible_files
        target: /home/ansible_controller/ansible_files
  target1:
    build: 
      context: ./hello-world
      dockerfile: Dockerfile
    container_name: react-app-capstone
    ports:
      - "3000:3000"

  