name: build-docker-image
on:
  push:
    branches:
      - "librado-dev"
  pull_request:
    branches:
      - "librado-dev"
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.13.1]
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install dependencies
      run: npm ci
      working-directory: ./capstone_project/hello-world
    - name: Run tests
      run: npm test
      working-directory: ./capstone_project/hello-world
    - name: Build container
      if: success()
      run: |
        docker build -t ITJ-react-app .
      working-directory: ./capstone_project/hello-world
    - name: Push to Docker Hub
      if: success()
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: my-dockerhub-username/ITJ-react-app:${{ github.sha }}
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}